### ISSUE TITLE
Error code : 9002

### ISSUE THREAD

**Issue by ITGuy1972** [microsoftgraph/windowsupdates-webapplication-sample#6]
Hi, I have followed the steps and tried running on a domain joined device and personal. The app installs and I can open localhost:3000, but when clicking the sign in box it appears for a millisecond then goes. The inspection shows
![image](https://github.com/microsoftgraph/windowsupdates-webapplication-sample/assets/135814631/6b338724-1557-452e-9415-5bbcfd1ff115)

All the details are correct, port 3000 is open and listening, but it thinks I am trying to access the wrong tenant ID or non existing, which is not true.

{"error":"invalid_tenant","error_description":"AADSTS90002: Tenant 'tenant_id' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant.\r\nTrace ID: e9a899ac-eed7-4828-a580-2c0b8ffb2100\r\nCorrelation ID: 22a58ae7-fe96-44eb-8610-5eeb970d5089\r\nTimestamp: 2023-06-07 08:06:56Z","error_codes":[90002],"timestamp":"2023-06-07 08:06:56Z","trace_id":"e9a899ac-eed7-4828-a580-2c0b8ffb2100","correlation_id":"22a58ae7-fe96-44eb-8610-5eeb970d5089","error_uri":"https://login.microsoftonline.com/error?code=90002"}

Any advice greatly appreciated as I would like to test / use this solution.

Thanks

**Comment by Ryan-K-Williams** [comment]
This sample has been archived and is no longer being maintained.  As part of the archival process, we're closing all open issues and pull requests.
